# Travis build script for mineman

# Use new container infrastructure to enable caching
sudo: false

# Use Maven
language: java

# Caching so the next build will be fast too.
cache:
  directories:
    - $HOME/.m2

# Set the final name using pom-fu
install:
  - mvn install -DfinalName=release -DskipTests=true -Dmaven.javadoc.skip=true -B -V

# You fill out this section by encrypting the key using the travis utility
# Note that the api_key is safe to put here because it is actually encrypted
#deploy:
  #provider: releases
  #api_key:
    #secure: <Your travis encrypted github release key here>
  #file: target/release.jar
  #skip_cleanup: true
  # Modify this to build on every commit
  #on:
    #tags: true